# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'MicroServiciosMP'
    scannerMode: 'Other'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo '### START: change the project version on pom.xml ###'
      echo 'Accessing to downloaded repo... '
      cd $(Build.Repository.LocalPath)
      pwd
      echo 'Showing all downloaded repo files... '
      ls -ltr
      echo 'Updating the project version... '
      /usr/share/apache-maven-3.6.3/bin/mvn versions:set -DnewVersion=$(artifact_version)
      echo 'Checking the changes... '
      ls -ltr
      echo 'Updated pom.xml content'
      cat pom.xml
      echo '### FINISH: updated pom.xml ###'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: '.jar'
    publishLocation: 'pipeline'